//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceTypeId { get; set; }
        public int AttendanceId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> MemberId { get; set; }
    
        public virtual AttendanceType AttendanceType { get; set; }
        public virtual Member Member { get; set; }
    }
}
