//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberZoneDetail
    {
        public int MemberId { get; set; }
        public int ZoneDetailId { get; set; }
        public int MemberZoneDetailId { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual ZoneDetail ZoneDetail { get; set; }
    }
}
