//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Attendances = new HashSet<Attendance>();
            this.MemberChilds = new HashSet<MemberChild>();
            this.MemberZoneDetails = new HashSet<MemberZoneDetail>();
        }
    
        public Nullable<int> TitleId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OtherName { get; set; }
        public string PrefferedName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string HomeAddress { get; set; }
        public string CellPhone { get; set; }
        public string WorkPhone { get; set; }
        public string Email { get; set; }
        public int OccupationId { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public int MembershipStatusId { get; set; }
        public Nullable<System.DateTime> BaptismDate { get; set; }
        public int MaritalStatusId { get; set; }
        public Nullable<System.DateTime> WeddingDate { get; set; }
        public string SpouseName { get; set; }
        public Nullable<int> NumberOFChildren { get; set; }
        public int MemberId { get; set; }
        public int SpouseOccupationId { get; set; }
        public string SpouseMembershipStatus { get; set; }
        public int MemberTypeId { get; set; }
        public Nullable<int> SpouseAge { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual MembershipStatu MembershipStatu { get; set; }
        public virtual MemberType MemberType { get; set; }
        public virtual Occupation Occupation { get; set; }
        public virtual Occupation Occupation1 { get; set; }
        public virtual Title Title { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberChild> MemberChilds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberZoneDetail> MemberZoneDetails { get; set; }
    }
}
