//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChurchProject.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoneDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZoneDetail()
        {
            this.MemberZoneDetails = new HashSet<MemberZoneDetail>();
        }
    
        public int ZoneId { get; set; }
        public int TownId { get; set; }
        public int ZoneDetailId { get; set; }
        public int ZoneHeadId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberZoneDetail> MemberZoneDetails { get; set; }
        public virtual Town Town { get; set; }
        public virtual Zone Zone { get; set; }
        public virtual ZoneHead ZoneHead { get; set; }
    }
}
